database:
  driverClass: com.google.cloud.spanner.jdbc.JdbcDriver
  user: ""
  password: ""
  url: jdbc:cloudspanner:/projects/demo-project/instances/demo-instance/databases/demo?usePlainText=true
  properties:
    maxWaitForConnection: 1s
    validationQuery: "/* MyService Health Check */ SELECT 1"
    minSize: 8
    maxSize: 32
    checkConnectionWhileIdle: false
    evictionInterval: 10s
    minIdleTime: 1 minute

hibernateConfiguration:
  hibernate.show_sql: true
  hibernate.dialect: com.google.cloud.spanner.hibernate.SpannerDialect
  hibernate.hbm2ddl.auto: create-drop
  hibernate.generate_statistics: false

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8082

logging:
  level: INFO
  loggers:
    com.surfsoftconsulting.dropwizard: DEBUG
    org.hibernate.SQL:
      level: DEBUG

  appenders:
    - type: console
