database:
  driverClass: com.google.cloud.spanner.jdbc.JdbcDriver
  user: ""
  password: ""
  url: jdbc:cloudspanner://localhost:9010/projects/demo-project/instances/demo-instance/databases/demo?usePlainText=true
  maxWaitForConnection: 5s
  maxSize: 32
  checkConnectionWhileIdle: false
  checkConnectionOnBorrow: true

hibernateConfiguration:
  hibernate.show_sql: true
  hibernate.dialect: com.google.cloud.spanner.hibernate.SpannerDialect
  hibernate.hbm2ddl.auto: create-drop
  hibernate.generate_statistics: false

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8082

logging:
  level: INFO
  loggers:
    com.surfsoftconsulting.dropwizard: DEBUG
    org.hibernate.SQL:
      level: DEBUG

  appenders:
    - type: console
