database:
  driverClass: org.h2.Driver
  user: "sa"
  password: ""
  url: jdbc:h2:mem:test;MODE=MYSQL;DATABASE_TO_UPPER=FALSE
  properties:
    charSet: UTF-8
    maxWaitForConnection: 1s
    validationQuery: "/* MyService Health Check */ SELECT 1"
    minSize: 8
    maxSize: 32
    checkConnectionWhileIdle: false
    evictionInterval: 10s
    minIdleTime: 1 minute
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.show_sql: true
    hibernate.generate_statistics: false
    hibernate.hbm2ddl.auto: create-drop

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8082

logging:
  level: INFO
  loggers:
    com.surfsoftconsulting.dropwizard: DEBUG
    org.hibernate.SQL:
      level: DEBUG

  appenders:
    - type: console
